
// This code is generated by maskaudit.py.  Do not hand-hack it!

/*
 * Also, beware that it is something of a CPU hog when called on every packet.
 * Try to write guards so it is only called at higher log levels.
 */

#include "../include/gpsd_config.h"  // must be before all includes

#include <stdio.h>
#include <string.h>

#include "../include/gpsd.h"

/* Convert gps_mask_t set to a string representation
 *
 * Return pointer to static buffer contatining the string.
 */
const char *gps_maskdump(gps_mask_t set)
{
    static char buf[249];
    const struct {
        gps_mask_t      mask;
        const char      *name;
    } *sp, names[] = {
        {AIS_SET,	"AIS"},
        {ALTITUDE_SET,	"ALTITUDE"},
        {ATTITUDE_SET,	"ATTITUDE"},
        {CLEAR_IS,	"CLEAR"},
        {CLIMBERR_SET,	"CLIMBERR"},
        {CLIMB_SET,	"CLIMB"},
        {DEVICEID_SET,	"DEVICEID"},
        {DEVICELIST_SET,	"DEVICELIST"},
        {DEVICE_SET,	"DEVICE"},
        {DOP_SET,	"DOP"},
        {DRIVER_IS,	"DRIVER"},
        {ECEF_SET,	"ECEF"},
        {EOF_IS,	"EOF"},
        {ERROR_SET,	"ERROR"},
        {GOODTIME_IS,	"GOODTIME"},
        {GST_SET,	"GST"},
        {HERR_SET,	"HERR"},
        {IMU_SET,	"IMU"},
        {LATLON_SET,	"LATLON"},
        {LOGMESSAGE_SET,	"LOGMESSAGE"},
        {LOG_SET,	"LOG"},
        {MAGNETIC_TRACK_SET,	"MAGNETIC_TRACK"},
        {MODE_SET,	"MODE"},
        {NAVDATA_SET,	"NAVDATA"},
        {NED_SET,	"NED"},
        {NODATA_IS,	"NODATA"},
        {NTPTIME_IS,	"NTPTIME"},
        {ONLINE_SET,	"ONLINE"},
        {OSCILLATOR_SET,	"OSCILLATOR"},
        {PACKET_SET,	"PACKET"},
        {PASSTHROUGH_IS,	"PASSTHROUGH"},
        {PERR_IS,	"PERR"},
        {POLICY_SET,	"POLICY"},
        {PPS_SET,	"PPS"},
        {RAW_IS,	"RAW"},
        {RAW_SET,	"RAW"},
        {REPORT_IS,	"REPORT"},
        {RTCM2_SET,	"RTCM2"},
        {RTCM3_SET,	"RTCM3"},
        {SATELLITE_SET,	"SATELLITE"},
        {SPEEDERR_SET,	"SPEEDERR"},
        {SPEED_SET,	"SPEED"},
        {STATUS_SET,	"STATUS"},
        {SUBFRAME_SET,	"SUBFRAME"},
        {TIMERR_SET,	"TIMERR"},
        {TIME_SET,	"TIME"},
        {TOFF_SET,	"TOFF"},
        {TRACKERR_SET,	"TRACKERR"},
        {TRACK_SET,	"TRACK"},
        {USED_IS,	"USED"},
        {VECEF_SET,	"VECEF"},
        {VERR_SET,	"VERR"},
        {VERSION_SET,	"VERSION"},
        {VNED_SET,	"VNED"},
    };

    memset(buf, '\0', sizeof(buf));
    buf[0] = '{';
    for (sp = names; sp < (names + sizeof(names)/sizeof(names[0])); sp++) {
        if ((gps_mask_t)0 != (set & sp->mask)) {
            if ('\0' != buf[1]) {
                (void)strlcat(buf, "|", sizeof(buf));
            }
            (void)strlcat(buf, sp->name, sizeof(buf));
        }
    }
    (void)strlcat(buf, "}", sizeof(buf));
    return buf;
}

